Resources: 
  ATUec2:  
    Type: AWS::EC2::Instance 
    Properties: 
      ImageId: ami-03c4f11b50838ab5d 
      InstanceType: t3.micro 
      KeyName: pgdipkeypair 
      Tags:
      - Key: Name 
        Value: Demo1
      - Key: CostCenter
        Value: Eng